### ISSUE TITLE
NotImplementedError: use ``sl.add(value)`` instead

### ISSUE THREAD

**Issue by quomap** [grantjenks/python-sortedcontainers#127]
```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 61269)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "server.py", line 18, in handle
    self.server.matching_engine.process(order)
  File "/Users/demo/matching_engine/engine.py", line 73, in process
    self.match_limit_order(order)
  File "/Users/demo/matching_engine/engine.py", line 108, in match_limit_order
    self.orderbook.add(Order(order.id, "limit", order.side, order.price, order.quantity-filled))
  File "/Users/demo/matching_engine/engine.py", line 53, in add
    self.bids.insert(index, order)
  File "/usr/local/lib/python3.7/site-packages/sortedcontainers/sortedlist.py", line 1304, in insert
    raise NotImplementedError('use ``sl.add(value)`` instead')
NotImplementedError: use ``sl.add(value)`` instead
----------------------------------------
```

and how to let sortedcontainers can list by order?

**Comment by grantjenks** [comment]
Change insert() to add() as suggested by the exception and it will work.

The sorted ordering of values is automatic.
