### ISSUE TITLE
Can not distinguish two different items with the same value

### ISSUE THREAD

**Issue by skypitcher** [grantjenks/python-sortedcontainers#161]
```python
from sortedcontainers import SortedList


class Result:
    def __init__(self, name, score, time):
        self.name = name
        self.score = score
        self.time = time

    def __repr__(self):
        return "Result<{} takes {} points in {} seconds>".format(self.name, self.score, self.time)

    def __hash__(self):
        return hash(self.name)

    def __eq__(self, other):
        return self.name == other.name

    def __lt__(self, other):
        if self.score == other.score:
            return self.time < other.time
        return self.score < other.score

    def __le__(self, other):
        if self.score == other.score:
            return self.time <= other.time
        return self.score < other.score


if __name__ == "__main__":
    harry = Result("Harry", 90, 180)
    lilly = Result("Lilly", 30, 150)
    gorden = Result("Gorden", 90, 180)

    results = SortedList([harry, lilly, gorden])
    print(results)
    results.remove(gorden)
```

Ouputs:
```
SortedList([Result<Lilly takes 30 points in 150 seconds>, Result<Harry takes 90 points in 180 seconds>, Result<Gorden takes 90 points in 180 seconds>])
Traceback (most recent call last):
  File "D:/ILS/hats/test_t.py", line 37, in <module>
    results.remove(gorden)
  File "C:\Program Files\Python36\lib\site-packages\sortedcontainers\sortedlist.py", line 462, in remove
    raise ValueError('{0!r} not in list'.format(value))
ValueError: Result<Gorden takes 90 points in 180 seconds> not in list
```

**Comment by skypitcher** [comment]
http://www.grantjenks.com/docs/sortedcontainers/introduction.html#caveats
