### ISSUE TITLE
TypeError: '<' not supported between instances of 'int' and 'str'

### ISSUE THREAD

**Issue by timborden** [grantjenks/python-sortedcontainers#218]
Trying to reverse sort a SortedDict with an integer key I get a `TypeError: '<' not supported between instances of 'int' and 'str'` error.

```
>>> from sortedcontainers import SortedDict
>>> test = SortedDict(key=lambda x: -x)
>>> test[1] = "foo"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...site-packages/sortedcontainers/sorteddict.py", line 299, in __setitem__
    self._list_add(key)
  File "...site-packages/sortedcontainers/sortedlist.py", line 272, in add
    pos = bisect_right(_maxes, value)
TypeError: '<' not supported between instances of 'int' and 'str'
```

Is this a bug? ....or am I setting up the key wrong?

**Comment by grantjenks** [comment]
To pass a key func, it must be positional else the kwargs are interpreted as a dict which is used for initialization. Read the docs for details
