### ISSUE TITLE
Modifying Keys In-Place Causes KeyError in SortedDict

### ISSUE THREAD

**Issue by rhseung** [grantjenks/python-sortedcontainers#229]
```py
from sortedcontainers import SortedDict
from dataclasses import dataclass

@dataclass
class A:
    x: int
    y: int

    def __hash__(self):
            return hash((self.x, self.y))
    def __eq__(self, other):
            return isinstance(other, A) and self.x == other.x and self.y == other.y
    def __lt__(self, other):
            if self.x == other.x:
                    return self.y < other.y
            else:
                    return self.x < other.x

o = SortedDict({A(3, 5): 4, A(6, 10): 8, A(2, 5): 3.5})
```
Declare `SortedDict` and hashable dataclass `A` like this.

```py
>>> print(o)
SortedDict({A(x=2, y=5): 3.5, A(x=3, y=5): 4, A(x=6, y=10): 8})
```
and I modified the key value.
```py
for k, v in o.items():
    k.y += 1

>>> print(o)
Traceback (most recent call last):
  File "c:\...\test.py", line 23, in <module>
    print(o)
  File "C:\...\Python311\Lib\site-packages\sortedcontainers\sortedlist.py", line 71, in wrapper
    result = user_function(self)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\...\Python311\Lib\site-packages\sortedcontainers\sorteddict.py", line 603, in __repr__
    items = ', '.join(item_format(key, self[key]) for key in self._list)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\Python311\Lib\site-packages\sortedcontainers\sorteddict.py", line 603, in <genexpr>
    items = ', '.join(item_format(key, self[key]) for key in self._list)
                                       ~~~~^^^^^
KeyError: A(x=2, y=6)
```
This error does not occur in builtin `dict`.

**Comment by grantjenks** [comment]
Read (2) at https://grantjenks.com/docs/sortedcontainers/introduction.html#caveats

You’ve broken the builtin implementation as well by modifying the key of an item in the dict. It just doesn’t fail when calling the repr.
